# Generated by Django 4.1 on 2022-08-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='cover',
        ),
    ]
