# Generated by Django 4.1 on 2022-08-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
    ]
