# Generated by Django 4.1 on 2022-08-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='content1',
            field=models.TextField(default='', verbose_name='content1'),
        ),
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default='', verbose_name='content2'),
        ),
        migrations.AddField(
            model_name='post',
            name='content3',
            field=models.TextField(default='', verbose_name='content3'),
        ),
    ]
