# Generated by Django 4.1 on 2022-08-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_content_post_content1_post_content2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentence',
            field=models.TextField(default='', verbose_name='sentence'),
        ),
    ]
