# Generated by Django 4.1 on 2022-08-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_sentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='cover1',
        ),
        migrations.AddField(
            model_name='post',
            name='cover2',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y%m%d'),
        ),
    ]
