# Generated by Django 4.1 on 2022-08-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_rename_cover_post_cover1_post_cover2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
    ]
