# Generated by Django 4.1 on 2022-08-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_post_cover2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content10',
            field=models.TextField(default='', verbose_name='content10'),
        ),
        migrations.AddField(
            model_name='post',
            name='content11',
            field=models.TextField(default='', verbose_name='content11'),
        ),
        migrations.AddField(
            model_name='post',
            name='content12',
            field=models.TextField(default='', verbose_name='content12'),
        ),
        migrations.AddField(
            model_name='post',
            name='content13',
            field=models.TextField(default='', verbose_name='content13'),
        ),
        migrations.AddField(
            model_name='post',
            name='content4',
            field=models.TextField(default='', verbose_name='content4'),
        ),
        migrations.AddField(
            model_name='post',
            name='content5',
            field=models.TextField(default='', verbose_name='content5'),
        ),
        migrations.AddField(
            model_name='post',
            name='content6',
            field=models.TextField(default='', verbose_name='content6'),
        ),
        migrations.AddField(
            model_name='post',
            name='content7',
            field=models.TextField(default='', verbose_name='content7'),
        ),
        migrations.AddField(
            model_name='post',
            name='content8',
            field=models.TextField(default='', verbose_name='content8'),
        ),
        migrations.AddField(
            model_name='post',
            name='content9',
            field=models.TextField(default='', verbose_name='content9'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover10',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover11',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover12',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover13',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover6',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover7',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover8',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover9',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
    ]
