# Generated by Django 4.1 on 2022-08-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_content10_post_content11_post_content12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content14',
            field=models.TextField(default='', verbose_name='content14'),
        ),
    ]
