# Generated by Django 4.1 on 2022-08-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_content14'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover13',
            new_name='coverorg',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content13',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content14',
        ),
        migrations.AddField(
            model_name='post',
            name='intro1',
            field=models.CharField(default='', max_length=150, verbose_name='intro1'),
        ),
        migrations.AddField(
            model_name='post',
            name='intro2',
            field=models.CharField(default='', max_length=150, verbose_name='intro2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%y%m%d'),
        ),
    ]
