# Generated by Django 4.1 on 2022-08-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_rename_cover13_post_coverorg_remove_post_content13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='outro',
            field=models.CharField(default='', max_length=150, verbose_name='outro'),
        ),
    ]
