# Generated by Django 4.1 on 2022-08-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_outro'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title1',
            field=models.CharField(default='', max_length=150, verbose_name='title1'),
        ),
        migrations.AddField(
            model_name='post',
            name='title10',
            field=models.CharField(default='', max_length=150, verbose_name='title10'),
        ),
        migrations.AddField(
            model_name='post',
            name='title11',
            field=models.CharField(default='', max_length=150, verbose_name='title11'),
        ),
        migrations.AddField(
            model_name='post',
            name='title12',
            field=models.CharField(default='', max_length=150, verbose_name='title12'),
        ),
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(default='', max_length=150, verbose_name='title2'),
        ),
        migrations.AddField(
            model_name='post',
            name='title3',
            field=models.CharField(default='', max_length=150, verbose_name='title3'),
        ),
        migrations.AddField(
            model_name='post',
            name='title4',
            field=models.CharField(default='', max_length=150, verbose_name='title4'),
        ),
        migrations.AddField(
            model_name='post',
            name='title5',
            field=models.CharField(default='', max_length=150, verbose_name='title5'),
        ),
        migrations.AddField(
            model_name='post',
            name='title6',
            field=models.CharField(default='', max_length=150, verbose_name='title6'),
        ),
        migrations.AddField(
            model_name='post',
            name='title7',
            field=models.CharField(default='', max_length=150, verbose_name='title7'),
        ),
        migrations.AddField(
            model_name='post',
            name='title8',
            field=models.CharField(default='', max_length=150, verbose_name='title8'),
        ),
        migrations.AddField(
            model_name='post',
            name='title9',
            field=models.CharField(default='', max_length=150, verbose_name='title9'),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro1',
            field=models.TextField(default='', verbose_name='intro1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro2',
            field=models.TextField(default='', verbose_name='intro2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='outro',
            field=models.TextField(default='', verbose_name='outro'),
        ),
    ]
