# Generated by Django 4.1 on 2022-08-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_post_title1_post_title10_post_title11_post_title12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content1',
            field=models.TextField(blank=True, default='', verbose_name='content1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content10',
            field=models.TextField(blank=True, default='', verbose_name='content10'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content11',
            field=models.TextField(blank=True, default='', verbose_name='content11'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content12',
            field=models.TextField(blank=True, default='', verbose_name='content12'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.TextField(blank=True, default='', verbose_name='content2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content3',
            field=models.TextField(blank=True, default='', verbose_name='content3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content4',
            field=models.TextField(blank=True, default='', verbose_name='content4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content5',
            field=models.TextField(blank=True, default='', verbose_name='content5'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content6',
            field=models.TextField(blank=True, default='', verbose_name='content6'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content7',
            field=models.TextField(blank=True, default='', verbose_name='content7'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content8',
            field=models.TextField(blank=True, default='', verbose_name='content8'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content9',
            field=models.TextField(blank=True, default='', verbose_name='content9'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title1',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title10',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title10'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title11',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title11'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title12',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title12'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title2',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title3',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title4',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title5',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title5'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title6',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title6'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title7',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title7'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title8',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title8'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title9',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='title9'),
        ),
    ]
