# Generated by Django 4.1 on 2022-08-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_post_content1_alter_post_content10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='semester',
            field=models.CharField(choices=[('tech', 'tech'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='tech', max_length=20),
        ),
    ]
