# Generated by Django 4.1 on 2022-08-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_post_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='semester',
            new_name='cat',
        ),
    ]
