# Generated by Django 4.1 on 2022-08-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_rename_semester_post_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link10',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link11',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link12',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link3',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link4',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link5',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link6',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link7',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link8',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link9',
            field=models.URLField(default=''),
        ),
    ]
