# Generated by Django 4.1 on 2022-08-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_post_link1_post_link10_post_link11_post_link12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link1',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link10',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link11',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link12',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link2',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link3',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link4',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link5',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link6',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link7',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link8',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link9',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
