# Generated by Django 4.1 on 2022-08-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_alter_post_link1_alter_post_link10_alter_post_link11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link1',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
