# Generated by Django 4.1 on 2022-08-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_alter_post_link1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link1',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
