# Generated by Django 4.1 on 2022-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_alter_post_link1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('technology', 'technology'), ('general', 'general'), ('self_improvement', 'self_improvement'), ('unsolved', 'unsolved'), ('health_fitness', 'health_fitness')], default='tech', max_length=20),
        ),
    ]
