# Generated by Django 4.1 on 2022-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_alter_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('technology', 'technology'), ('general', 'general'), ('self improvement', 'self improvement'), ('unsolved', 'unsolved'), ('health & fitness', 'health & fitness')], default='tech', max_length=20),
        ),
    ]
