# Generated by Django 4.1 on 2022-08-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_alter_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Technology', 'Technology'), ('General', 'General'), ('Self-improvement', 'Self-improvement'), ('Unsolved', 'Unsolved'), ('Health&Fitness', 'Health&Fitness')], default='tech', max_length=20),
        ),
    ]
