# Generated by Django 4.1 on 2022-11-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_alter_post_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='DescSEO',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='DescSEO'),
        ),
        migrations.AddField(
            model_name='post',
            name='PostURL',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='PostURL'),
        ),
        migrations.AddField(
            model_name='post',
            name='keywordsSEO',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='keywordsSEO'),
        ),
    ]
